# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f58cf968657deddb83f0cb7a7e2c79e490f733b0e5e7f44b8ed9938bfede51ff80e7046621f2203a3f1ccb8ab885654d9fed03c47cc81bcbc26a5b9d579d20fa

test:
  secret_key_base: d1855a36e835fe13e37b172c2481615a5404822fb677a509a5a47817c192f4e00b3bf3600f6ec40dc5bc8685807b05f811231e0888edb5983730bbd44666344b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
